//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCjsonTesti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treenihistoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treenihistoria()
        {
            this.Treenihistoriarivit = new HashSet<Treenihistoriarivit>();
        }
    
        public int TreenihistoriaID { get; set; }
        public Nullable<System.DateTime> Pvm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treenihistoriarivit> Treenihistoriarivit { get; set; }
    }
}
