//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCjsonTesti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treenihistoriarivit
    {
        public int TreenihistoriariviID { get; set; }
        public int TreenihistoriaID { get; set; }
        public int LiikeID { get; set; }
        public int Sarjat { get; set; }
        public decimal Painot { get; set; }
    
        public virtual Treenihistoria Treenihistoria { get; set; }
    }
}
